version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hoa-admin-ui-nginx
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge